name: Build & Deploy Spring App - Github Actions

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Unit Tests
        run: 'mvn test'

      - name: Build the application
        run: 'mvn clean && mvn package'
    
